core/src/main/java/com/lafaspot/imapnio/client/IMAPChannelListener.java
core/src/main/java/com/lafaspot/imapnio/client/IMAPSession.java

fixes the disconnect on DONE command

fix log and add listener to raw command

---

core/src/main/java/com/lafaspot/imapnio/client/IMAPChannelListener.java
core/src/main/java/com/lafaspot/imapnio/client/IMAPClient.java
core/src/main/java/com/lafaspot/imapnio/client/IMAPSession.java
core/src/main/java/com/lafaspot/imapnio/client/SessionLogContext.java

Updated Kumar's patch with checkstyle and logfast changes. Added
a IMAPSession identifier which helps in debugging individual user
session command flow

Add debug id for session - updated kr patch

---

core/pom.xml
core/src/main/java/com/lafaspot/imapnio/client/IMAPSession.java
pom.xml

- Upgraded to netty 4.0.1.Beta5
- Upgraded version to 1.0.6

Upgraded to netty 4.0.1.Beta5

---

core/pom.xml
core/src/main/java/com/lafaspot/imapnio/client/IMAPSession.java
core/src/test/java/com/lafaspot/imapnio/client/ImapClientIT.java
logback.xml
pom.xml

Added logback.xml, fixed logging for ImapClientIT.

Added LIST support

---

core/pom.xml
core/src/main/java/com/lafaspot/imapnio/client/IMAPClient.java
core/src/main/java/com/lafaspot/imapnio/client/IMAPClientRespHandler.java
core/src/main/java/com/lafaspot/imapnio/client/IMAPSession.java
core/src/test/java/com/lafaspot/imapnio/client/ImapClientIT.java
pom.xml

- added shutdown to IMAPClient, moved EventLoop group shutdown to thereand out of session
- removed EventLoop group shutdown from session disconnect()
- storing current/idle tag 
- renamed getClientListener to getCommandListener

Added rawCommnd back, cleanup.

---

core/pom.xml
core/src/main/java/com/lafaspot/imapnio/channel/IMAPChannelFuture.java
core/src/main/java/com/lafaspot/imapnio/client/IMAPChannelListener.java
core/src/main/java/com/lafaspot/imapnio/client/IMAPClient.java
core/src/main/java/com/lafaspot/imapnio/client/IMAPClientInitializer.java
core/src/main/java/com/lafaspot/imapnio/client/IMAPClientRespHandler.java
core/src/main/java/com/lafaspot/imapnio/client/IMAPSession.java
core/src/main/java/com/lafaspot/imapnio/listener/IMAPChannelFutureListener.java
core/src/main/java/com/lafaspot/imapnio/listener/IMAPCommandListener.java
core/src/main/java/com/lafaspot/imapnio/listener/IMAPConnectionListener.java
core/src/test/java/com/lafaspot/imapnio/client/ImapClientIT.java
pom.xml

- added cancel to Future
- changed command/connection listener

Ver 1.0.10

---

core/pom.xml
core/src/main/java/com/lafaspot/imapnio/client/IMAPSession.java
core/src/main/java/com/lafaspot/imapnio/command/ProxyProtocol.java
core/src/test/java/com/lafaspot/imapnio/client/ImapClientIT.java
pom.xml

- Changed ProxyProtocol to support async-read-mode
- Changed executeCommand handling of oauth token
- increased version to 1.0.12

Outlook xoauth2 login fixes.

---

core/pom.xml
core/src/main/java/com/lafaspot/imapnio/client/IMAPSession.java
core/src/test/java/com/lafaspot/imapnio/client/ImapClientIT.java
pom.xml

- connect() takes local IP interface to bind to
- added ID command 
- increased version to 1.0.14

Added ID command & multiple interface support.

---

core/pom.xml
core/src/main/java/com/lafaspot/imapnio/client/IMAPClientRespHandler.java
core/src/test/java/com/lafaspot/imapnio/client/ImapClientIT.java
pom.xml

- increased version to 15
- clearing cached response even when response handler is NULL

Clearing response list on a tagged response at all times.

---

core/pom.xml
core/src/main/java/com/lafaspot/imapnio/client/IMAPClient.java
core/src/main/java/com/lafaspot/imapnio/client/IMAPClientInactivityHandler.java
core/src/main/java/com/lafaspot/imapnio/client/IMAPClientInitializer.java
core/src/main/java/com/lafaspot/imapnio/client/IMAPClientRespHandler.java
core/src/main/java/com/lafaspot/imapnio/client/IMAPSession.java
core/src/main/java/com/lafaspot/imapnio/listener/IMAPConnectionListener.java
core/src/test/java/com/lafaspot/imapnio/client/ImapClientIT.java
pom.xml

- Fixed multi-thread issues
- Added inactivity timeout capability
- Increased version to 17

Add inactivity timer callback.

---

pom.xml

update logfast for better memory management

---

core/pom.xml
core/src/main/java/com/lafaspot/imapnio/client/IMAPClientInitializer.java
core/src/main/java/com/lafaspot/imapnio/client/IMAPClientRespHandler.java
core/src/main/java/com/lafaspot/imapnio/client/IMAPSession.java
core/src/main/java/com/lafaspot/imapnio/command/ImapClientRespDecoder.java
core/src/test/java/com/lafaspot/imapnio/client/ImapClientIT.java
core/src/test/java/com/lafaspot/imapnio/client/ImapMultiConnectIT.java
pom.xml

- each channel pipeline is setup after connect
- added IT to test multiple connect request
- fixed current tag handling when connected
- fixed NPE on executeCommand during logout

Changed channel pipeline initialization.

---

core/pom.xml
core/src/main/java/com/lafaspot/imapnio/client/IMAPSession.java
pom.xml

- set the channel reference before giving onConnect callback to the
listener.
- up the version to 1.0.20

Change onConnect handling:

---

core/pom.xml
pom.xml

Changed netty dependency to use only netty-handler, instead of netty-all

Changed netty dependency to use only netty-handler, instead of netty-all

---

core/pom.xml
pom.xml

Hi,
This is a little PR that upgrade netty to a stable version.
We need this in our gatling-imap project.
Regards,
Raphaël Ouazana.

Upgrade Netty to Final version

---

core/src/main/java/com/lafaspot/imapnio/async/exception/package-info.java

Test travis pipeline

---

README.md
core/pom.xml
core/src/main/java/com/yahoo/imapnio/async/data/SearchResult.java
core/src/main/java/com/yahoo/imapnio/async/internal/ImapAsyncSessionImpl.java
core/src/main/java/com/yahoo/imapnio/async/response/ImapResponseMapper.java
core/src/test/java/com/yahoo/imapnio/async/internal/ImapAsyncSessionImplTest.java
core/src/test/java/com/yahoo/imapnio/async/response/ImapResponseMapperTest.java
pom.xml

Bug fix - Close session when encountering channel exception.

---

README.md
core/pom.xml
core/src/main/java/com/yahoo/imapnio/async/internal/ImapAsyncSessionImpl.java
core/src/test/java/com/yahoo/imapnio/async/internal/ImapAsyncSessionImplTest.java
pom.xml

1. Fix NPE in setDebugMode() when session is closed.  
2. Also add logging when session is closed.

Fix NPE in setDebugMode() when session is closed.  

---

README.md
core/pom.xml
core/src/main/java/com/yahoo/imapnio/async/request/AuthOauthBearerCommand.java
core/src/main/java/com/yahoo/imapnio/async/request/AuthPlainCommand.java
core/src/main/java/com/yahoo/imapnio/async/request/ImapCommandType.java
core/src/test/java/com/yahoo/imapnio/async/request/AuthOauthBearerCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/AuthPlainCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/UidFetchCommandTest.java
pom.xml

Add  Authenticate OAUTHBEARER command.

Support Authenticate OAUTHBEARER command.

---

README.md
core/pom.xml
core/src/main/java/com/yahoo/imapnio/async/data/ExtensionMailboxInfo.java
core/src/main/java/com/yahoo/imapnio/async/response/ImapResponseMapper.java
core/src/test/java/com/yahoo/imapnio/async/data/ExtensionMailboxInfoTest.java
core/src/test/java/com/yahoo/imapnio/async/response/ImapResponseMapperTest.java
pom.xml

Support MAILBOXID in ExtensionMailboxInfo.

---

README.md
core/pom.xml
core/src/main/java/com/yahoo/imapnio/async/response/ImapResponseMapper.java
core/src/main/java/com/yahoo/imapnio/client/ImapClientRespReader.java
core/src/test/java/com/yahoo/imapnio/async/response/ImapResponseMapperTest.java
pom.xml

1. Fix buffer reference count once finishing using from pooled buffer
2. Fix possible parsing errors

Bugs fixes.

---

README.md
core/pom.xml
core/src/main/java/com/yahoo/imapnio/async/request/EnableCommand.java
core/src/main/java/com/yahoo/imapnio/async/request/ImapCommandType.java
core/src/test/java/com/yahoo/imapnio/async/request/EnableCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/ImapCommandTypeTest.java
pom.xml

Add enable command

---

README.md
core/pom.xml
core/src/main/java/com/yahoo/imapnio/async/client/ImapAsyncClient.java
core/src/main/java/com/yahoo/imapnio/async/exception/ImapAsyncClientException.java
core/src/main/java/com/yahoo/imapnio/async/internal/ImapAsyncSessionImpl.java
core/src/main/java/com/yahoo/imapnio/async/netty/ImapClientConnectHandler.java
core/src/test/java/com/yahoo/imapnio/async/client/ImapAsyncClientTest.java
core/src/test/java/com/yahoo/imapnio/async/client/ImapAsyncCreateSessionResponseTest.java
core/src/test/java/com/yahoo/imapnio/async/exception/ImapAsyncClientExceptionTest.java
core/src/test/java/com/yahoo/imapnio/async/internal/ImapAsyncSessionImplTest.java
core/src/test/java/com/yahoo/imapnio/async/netty/ImapClientConnectHandlerTest.java
pom.xml

1. add session id and user id in exception getMessage()
2. add user id in debug/error logging

Improve logging.

---

README.md
core/pom.xml
core/src/main/java/com/yahoo/imapnio/async/internal/ImapAsyncSessionImpl.java
core/src/main/java/com/yahoo/imapnio/async/request/AbstractAuthCommand.java
core/src/main/java/com/yahoo/imapnio/async/request/AuthOauthBearerCommand.java
core/src/main/java/com/yahoo/imapnio/async/request/AuthPlainCommand.java
core/src/main/java/com/yahoo/imapnio/async/request/AuthXoauth2Command.java
core/src/main/java/com/yahoo/imapnio/async/request/ImapClientConstants.java
core/src/test/java/com/yahoo/imapnio/async/internal/ImapAsyncSessionImplTest.java
core/src/test/java/com/yahoo/imapnio/async/request/AuthOauthBearerCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/AuthPlainCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/AuthXoauth2CommandTest.java
pom.xml

1. We will send cancel response when server sends server challenge after client response is sent.
2. Before we did not log server challenge, this change will truly log both sever challenge and client cancel.

Bugs fixes for handling server challenge

---

README.md
core/pom.xml
core/src/main/java/com/yahoo/imapnio/async/data/QResyncParameter.java
core/src/main/java/com/yahoo/imapnio/async/data/QResyncSeqMatchData.java
core/src/main/java/com/yahoo/imapnio/async/request/AbstractFolderActionCommand.java
core/src/main/java/com/yahoo/imapnio/async/request/ExamineFolderCommand.java
core/src/main/java/com/yahoo/imapnio/async/request/OpenFolderActionCommand.java
core/src/main/java/com/yahoo/imapnio/async/request/SelectFolderCommand.java
core/src/test/java/com/yahoo/imapnio/async/data/QResyncParameterTest.java
core/src/test/java/com/yahoo/imapnio/async/data/QResyncSeqMatchDataTest.java
core/src/test/java/com/yahoo/imapnio/async/request/ExamineFolderCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/SelectFolderCommandTest.java
pom.xml

Added QRESYNC parameter to support QRESYNC
Select/Examine command can send additional QRESYNC parameter when QRESYNC is supported. To support client to send that parameter added new classes.
Added unit tests to verify
- [ X] New feature (non-breaking change which adds functionality)
- [ X] My code follows the code style of this project.
- [ X] My change requires a change to the documentation.
- [ X] I have updated the documentation accordingly.
- [ X] I have read the **CONTRIBUTING** document.
- [ X] I have added tests to cover my changes.
- [ X] All new and existing tests passed.

Add QRESYNC parameter

---

core/src/main/java/com/yahoo/imapnio/async/exception/ImapAsyncClientException.java
core/src/test/java/com/yahoo/imapnio/async/client/ImapAsyncClientTest.java
core/src/test/java/com/yahoo/imapnio/async/data/MessageNumberSetTest.java
core/src/test/java/com/yahoo/imapnio/async/exception/ImapAsyncClientExceptionTest.java
core/src/test/java/com/yahoo/imapnio/async/internal/ImapAsyncSessionImplTest.java
core/src/test/java/com/yahoo/imapnio/async/netty/ImapClientConnectHandlerTest.java
core/src/test/java/com/yahoo/imapnio/async/request/AppendCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/AuthOauthBearerCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/AuthPlainCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/AuthXoauth2CommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/CapaCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/EnableCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/FetchCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/IdCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/ImapArgumentFormatterByteBufTest.java
core/src/test/java/com/yahoo/imapnio/async/request/ImapArgumentFormatterTest.java
core/src/test/java/com/yahoo/imapnio/async/request/LSubCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/ListCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/LoginCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/SearchCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/StatusCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/StoreFlagsCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/UidSearchCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/response/ImapResponseMapperTest.java

Change-Id: Ic96b0a39dddf003db252c4619ad02a4db0ff0bfd
Fixing typo getFaiureType to getFailureType

Fixing a typo

---

README.md
core/pom.xml
pom.xml

Change-Id: I6c27723461c51ce2f630267a21b49986979e2245

Update major version to 4.0.0

---

README.md
core/pom.xml
pom.xml

Upgrade Jacoco version
Upgrade Jacoco version to avoid test coverage for enum value() function and private constructor
Pass all unit tests with higher coverage requirement.

Upgrade Jacoco Version

---

core/src/main/java/com/yahoo/imapnio/async/client/ImapAsyncClient.java
core/src/main/java/com/yahoo/imapnio/async/exception/ImapAsyncClientException.java
core/src/test/java/com/yahoo/imapnio/async/client/ImapAsyncClientTest.java
core/src/test/java/com/yahoo/imapnio/async/exception/ImapAsyncClientExceptionTest.java

Clients may have pre-configured SSLContext (JDK) that have their own implementation like KeyManagers or TrustManagers.  This support allows client to re-use the existing one .

Support mtls from pre-configured SSLContext

---

README.md
core/pom.xml
core/src/main/java/com/yahoo/imapnio/async/request/ImapRequest.java
pom.xml

Fix imap command type

---

README.md
core/pom.xml
core/src/main/java/com/yahoo/imapnio/async/client/ImapAsyncClient.java
pom.xml

Change-Id: Ie08adaaa9a402ba31e7d11c37b05fa38f7f51479

Fix preconfig sslcontext to use advisory peer information.

---

README.md
core/pom.xml
core/src/main/java/com/yahoo/imapnio/async/client/ImapAsyncClient.java
core/src/main/java/com/yahoo/imapnio/async/internal/ImapAsyncSessionImpl.java
core/src/main/java/com/yahoo/imapnio/async/netty/ImapClientConnectHandler.java
core/src/test/java/com/yahoo/imapnio/async/client/ImapAsyncClientTest.java
core/src/test/java/com/yahoo/imapnio/async/client/ImapAsyncCreateSessionResponseTest.java
core/src/test/java/com/yahoo/imapnio/async/internal/ImapAsyncSessionImplTest.java
core/src/test/java/com/yahoo/imapnio/async/netty/ImapClientConnectHandlerTest.java
pom.xml

Provide better information in CHANNEL_TIMEOUT exception.

Better logging for channel timeout exception.

---

README.md
core/pom.xml
core/src/main/java/com/yahoo/imapnio/async/internal/ImapAsyncSessionImpl.java
core/src/test/java/com/yahoo/imapnio/async/internal/ImapAsyncSessionImplTest.java
pom.xml

When ImapAsyncClientException is thrown during the session, we will give the command tag, command type, and the command sent time in the exception message.
- [] Bug fix (non-breaking change which fixes an issue)
- [] Breaking change (fix or feature that would cause existing functionality to change)
- [] Major release (change is NOT backward compatible with prior release)

Fix to give ImapAsyncClientException message with more context.

---

README.md
core/pom.xml
core/src/test/java/com/yahoo/imapnio/async/request/SearchCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/UidSearchCommandTest.java
pom.xml

This PR is to upgrade the netty version and fix some incorrect UT code.

Upgrade to higher Netty version.

---

README.md
core/pom.xml
core/src/main/java/com/yahoo/imapnio/async/data/ExtensionListInfo.java
core/src/main/java/com/yahoo/imapnio/async/data/ListStatusResult.java
core/src/main/java/com/yahoo/imapnio/async/request/ImapRFCSupportedCommandType.java
core/src/main/java/com/yahoo/imapnio/async/request/ListStatusCommand.java
core/src/main/java/com/yahoo/imapnio/async/response/ImapResponseMapper.java
core/src/test/java/com/yahoo/imapnio/async/data/ExtensionListInfoTest.java
core/src/test/java/com/yahoo/imapnio/async/data/ListStatusResultTest.java
core/src/test/java/com/yahoo/imapnio/async/request/ImapRFCSupportedCommandTypeTest.java
core/src/test/java/com/yahoo/imapnio/async/request/ListStatusCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/response/ImapResponseMapperTest.java
pom.xml

Support LIST-STATUS capability, RFC5819.

Support LIST-STATUS capability, RFC5819.

---

README.md
core/pom.xml
pom.xml

There is no code change involved.

Bumping out pom version due to travis push errors.

---

pom.xml

Revert "Bump logback-core from 1.1.3 to 1.2.0"

---

README.md
core/pom.xml
pom.xml

Upgrade logback from 1.1.3 to 1.2.0 for security
1.1.3 logback has security issues and need to be tested

Upgrade logback from 1.1.3 to 1.2.0 for security

---

README.md
core/pom.xml
core/src/main/java/com/yahoo/imapnio/async/data/EnableResult.java
core/src/main/java/com/yahoo/imapnio/async/response/ImapResponseMapper.java
core/src/test/java/com/yahoo/imapnio/async/data/EnableResultTest.java
core/src/test/java/com/yahoo/imapnio/async/response/ImapResponseMapperTest.java
pom.xml

Support parse Enable command response, add EnableResult class and its parser
Support parse Enable command response for ENABLE command

Support parse Enable command response

---

core/src/main/java/com/yahoo/imapnio/async/client/ImapFuture.java
core/src/test/java/com/yahoo/imapnio/async/client/ImapFutureTest.java

This allow avoiding blocking in calling code to unwrap the future
and access the inner value. This empowers reactive/asynchronous/actor
systems integrations.
I chose the callback approach instead of using CompletableFuture in
order to minimize code changes.
Adds callbacks to ImapFuture
Needs to call ImapFuture.get to do anything usefull with this library however it blocks and defeat any reactive/asynchronous/actor system use of this library.
Unit test. I will also ensure timely that this solves my original issue.
Javadoc.

ISSUE-86 Allow passing callbacks to ImapFuture

---

README.md
core/pom.xml
pom.xml

Upgrade version to 4.3.8 to include latest callback changes
Upgrade version to 4.3.8 to include latest callback changes

Upgrade version to 4.3.8 to include latest callback changes

---

README.md
core/pom.xml
core/src/main/java/com/yahoo/imapnio/async/internal/ImapAsyncSessionImpl.java
core/src/main/java/com/yahoo/imapnio/async/response/ImapAsyncResponse.java
core/src/test/java/com/yahoo/imapnio/async/client/ImapFutureTest.java
core/src/test/java/com/yahoo/imapnio/async/internal/ImapAsyncSessionImplTest.java
core/src/test/java/com/yahoo/imapnio/async/response/ImapAsyncResponseTest.java
pom.xml

Support request total bytes and response total bytes counting
Support request total bytes and response total bytes counting
Change has been tested by static main function and verified with IMAP access log for bytes sent and received.

Support request total bytes and response total bytes counting

---

README.md
checkstyle.xml
core/pom.xml
core/src/main/java/com/yahoo/imapnio/async/client/ImapAsyncSession.java
core/src/main/java/com/yahoo/imapnio/async/request/OpenFolderActionCommand.java
findbugs-exclude.xml
pom.xml
spotbugs-exclude.xml
spotbugs-include.xml

Increase maven package version
Increase maven package version
Update maven package version to include latest features

Increase maven package version

---

README.md
core/pom.xml
core/src/main/java/com/yahoo/imapnio/async/data/PartialExtensionUidFetchInfo.java
core/src/main/java/com/yahoo/imapnio/async/request/AbstractFetchCommand.java
core/src/main/java/com/yahoo/imapnio/async/request/UidFetchCommand.java
core/src/test/java/com/yahoo/imapnio/async/data/PartialExtensionUidFetchInfoTest.java
core/src/test/java/com/yahoo/imapnio/async/request/UidFetchCommandTest.java
pom.xml

Support partial extension UID fetch.

Support partial extension UID fetch.

---

README.md
core/pom.xml
pom.xml

Upgrade package version
resolve vulnerabilities detected by sonatypelift
(https://sbom.lift.sonatype.com/report/T1-a0368c8f29fdaa555824-ad3735bf08fd6-1666888647-9b02343eb4f74f81b0e8399d6d4f699c)

Upgrade package version to reduce vulnerabilities

---

README.md
core/pom.xml
pom.xml

Fix CVE-2022-4065
https://github.com/advisories/GHSA-rc2q-x9mf-w3vf
Fix CVE-2022-4065
https://github.com/advisories/GHSA-rc2q-x9mf-w3vf
Security issue

Fix TestNG is vulnerable to Path Traversal

---

core/pom.xml

Keep it as a testing dependency
```
java.lang.NoSuchMethodError: 'java.lang.String ch.qos.logback.core.util.EnvUtil.logbackVersion()'
at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:81)
at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:77)
at ch.qos.logback.classic.spi.LogbackServiceProvider.initializeLoggerContext(LogbackServiceProvider.java:50)
at ch.qos.logback.classic.spi.LogbackServiceProvider.initialize(LogbackServiceProvider.java:41)
at org.slf4j.LoggerFactory.bind(LoggerFactory.java:183)
at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:170)
at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:455)
at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:441)
at …
```

ISSUE-145 Remove logback from main dependencies

---

core/src/main/java/com/yahoo/imapnio/async/internal/ImapAsyncSessionImpl.java
core/src/main/java/com/yahoo/imapnio/async/request/CompressCommand.java
core/src/test/java/com/yahoo/imapnio/async/internal/CompressCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/CompressCommandTest.java

Move CompressCommand class to com.yahoo.imapnio.async.request package.

Move CompressCommand class to com.yahoo.imapnio.async.request package.

---

README.md
core/pom.xml
pom.xml

Increase version for compress command
Increase version for compress command

Increase version for compress command

---

README.md
core/pom.xml
pom.xml

Remove unnecessary log4j
Remove unnecessary log4j
https://github.com/yahoo/imapnio/issues/145

Remove unnecessary log4j

---

pom.xml

Add vm argument for JDK new version
Add vm argument for JDK new version

Add vm argument for JDK new version

---

core/src/main/java/com/yahoo/imapnio/async/client/ImapAsyncSession.java
core/src/main/java/com/yahoo/imapnio/async/internal/ImapAsyncSessionImpl.java
core/src/test/java/com/yahoo/imapnio/async/internal/ImapAsyncSessionImplTest.java

I would like to assert the state of a session before submitting requests to it.
IMAP provisionning script
All tests passes

ISSUE-147 isChannelClosed should be public

---

README.md
core/pom.xml
pom.xml

Publish new imapnio version with latest changes
Publish new imapnio version with latest changes

Publish new imapnio version with latest changes

---

pom.xml

Netty and commons-codec jar upgraded to the latest version in pom.xml

Netty and commoms-codec jar upgraded in pom.xml

---

README.md
core/pom.xml
pom.xml

Fix gpg sign failure
Fix gpg sign failure
Fix gpg sign failure

Fix gpg sign failure

---

README.md
core/pom.xml
core/src/main/java/com/yahoo/imapnio/async/client/ImapAsyncClient.java
core/src/main/java/com/yahoo/imapnio/async/netty/ImapClientConnectHandler.java
core/src/main/java/com/yahoo/imapnio/async/request/ImapClientConstants.java
core/src/test/java/com/yahoo/imapnio/async/client/ImapAsyncClientTest.java
core/src/test/java/com/yahoo/imapnio/async/netty/ImapClientCommandRespHandlerTest.java
core/src/test/java/com/yahoo/imapnio/async/netty/ImapClientConnectHandlerTest.java
core/src/test/java/com/yahoo/imapnio/async/request/SearchCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/UidCopyMessageCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/UidMoveMessageCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/request/UidSearchCommandTest.java
core/src/test/java/com/yahoo/imapnio/async/response/ImapResponseMapperTest.java
pom.xml

Upgrade mvn package version
Upgrade mvn package version

Upgrade mvn package version

---

Code-of-Conduct.md
pom.xml

Update pom and COC to latest info
